<?php

declare(strict_types=1);



return ['up' => static function (PDO $pdo): void {
    $queries = [
        "CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB",
        "CREATE TABLE permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB",
        "CREATE TABLE role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id, permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB",
        "CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role_id BIGINT UNSIGNED NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB",
        "CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(100) NOT NULL, module_name VARCHAR(80) NOT NULL, record_id BIGINT UNSIGNED NULL, context_json JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(module_name, record_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE customers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, customer_code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, mobile VARCHAR(30) NULL, email VARCHAR(190) NULL, gender VARCHAR(20) NULL, notes TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(mobile), INDEX(name)) ENGINE=InnoDB",
        "CREATE TABLE staff (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, staff_code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, mobile VARCHAR(30) NULL, designation VARCHAR(100) NULL, commission_type ENUM('percentage','fixed') NOT NULL DEFAULT 'percentage', commission_value DECIMAL(12,2) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB",
        "CREATE TABLE service_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "CREATE TABLE services (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, service_code VARCHAR(30) NOT NULL UNIQUE, category_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, duration_minutes INT UNSIGNED NOT NULL DEFAULT 30, price DECIMAL(12,2) NOT NULL, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0, commission_type ENUM('percentage','fixed') NOT NULL DEFAULT 'percentage', commission_value DECIMAL(12,2) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, FOREIGN KEY(category_id) REFERENCES service_categories(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE product_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "CREATE TABLE suppliers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, supplier_code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, mobile VARCHAR(30) NULL, company VARCHAR(150) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_code VARCHAR(30) NOT NULL UNIQUE, category_id BIGINT UNSIGNED NULL, supplier_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, sku VARCHAR(80) NULL UNIQUE, selling_price DECIMAL(12,2) NOT NULL, purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0, current_stock DECIMAL(12,3) NOT NULL DEFAULT 0, minimum_stock DECIMAL(12,3) NOT NULL DEFAULT 0, unit VARCHAR(20) NOT NULL DEFAULT 'pcs', is_active TINYINT(1) NOT NULL DEFAULT 1, FOREIGN KEY(category_id) REFERENCES product_categories(id) ON DELETE SET NULL, FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE appointments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, appointment_code VARCHAR(30) NOT NULL UNIQUE, customer_id BIGINT UNSIGNED NOT NULL, staff_id BIGINT UNSIGNED NULL, start_at DATETIME NOT NULL, end_at DATETIME NOT NULL, status ENUM('pending','confirmed','checked_in','in_progress','completed','cancelled','no_show') NOT NULL DEFAULT 'pending', notes TEXT NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(staff_id,start_at,end_at,status), FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(staff_id) REFERENCES staff(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE appointment_services (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, appointment_id BIGINT UNSIGNED NOT NULL, service_id BIGINT UNSIGNED NOT NULL, staff_id BIGINT UNSIGNED NULL, price DECIMAL(12,2) NOT NULL, duration_minutes INT UNSIGNED NOT NULL, FOREIGN KEY(appointment_id) REFERENCES appointments(id) ON DELETE CASCADE, FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(staff_id) REFERENCES staff(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE invoices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_number VARCHAR(40) NOT NULL UNIQUE, customer_id BIGINT UNSIGNED NOT NULL, cashier_id BIGINT UNSIGNED NULL, appointment_id BIGINT UNSIGNED NULL UNIQUE, status ENUM('finalized','cancelled') NOT NULL DEFAULT 'finalized', subtotal DECIMAL(12,2) NOT NULL, discount_total DECIMAL(12,2) NOT NULL DEFAULT 0, tax_total DECIMAL(12,2) NOT NULL DEFAULT 0, rounding DECIMAL(12,2) NOT NULL DEFAULT 0, grand_total DECIMAL(12,2) NOT NULL, paid_total DECIMAL(12,2) NOT NULL DEFAULT 0, balance_total DECIMAL(12,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(cashier_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(appointment_id) REFERENCES appointments(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE invoice_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, line_no INT UNSIGNED NOT NULL, item_type ENUM('service','product') NOT NULL, service_id BIGINT UNSIGNED NULL, product_id BIGINT UNSIGNED NULL, staff_id BIGINT UNSIGNED NULL, description VARCHAR(255) NOT NULL, quantity DECIMAL(12,3) NOT NULL, unit_price DECIMAL(12,2) NOT NULL, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0, tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0, line_total DECIMAL(12,2) NOT NULL, UNIQUE(invoice_id,line_no), FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE, FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(staff_id) REFERENCES staff(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE payment_methods (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, payment_code VARCHAR(40) NOT NULL UNIQUE, invoice_id BIGINT UNSIGNED NOT NULL, payment_method_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL, reference_no VARCHAR(100) NULL, received_by BIGINT UNSIGNED NULL, paid_at DATETIME NOT NULL, status ENUM('captured','void') NOT NULL DEFAULT 'captured', FOREIGN KEY(invoice_id) REFERENCES invoices(id), FOREIGN KEY(payment_method_id) REFERENCES payment_methods(id), FOREIGN KEY(received_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE stock_movements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, movement_type ENUM('purchase','sale','adjustment','damage','return_in','return_out') NOT NULL, quantity DECIMAL(12,3) NOT NULL, before_quantity DECIMAL(12,3) NOT NULL, after_quantity DECIMAL(12,3) NOT NULL, reference_type VARCHAR(40) NULL, reference_id BIGINT UNSIGNED NULL, reason VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(product_id,created_at), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE expenses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, expense_code VARCHAR(30) NOT NULL UNIQUE, description VARCHAR(255) NOT NULL, amount DECIMAL(12,2) NOT NULL, expense_date DATE NOT NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(100) NOT NULL UNIQUE, setting_value TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB",
    ];
    foreach ($queries as $query) { $pdo->exec($query); }
    $pdo->exec("INSERT INTO roles (name) VALUES ('Super Admin'),('Manager'),('Cashier'),('Staff')");
    $pdo->exec("INSERT INTO payment_methods (code,name) VALUES ('cash','Cash'),('upi','UPI'),('card','Card'),('bank','Bank Transfer')");
    $pdo->exec("INSERT INTO settings (setting_key,setting_value) VALUES ('business_name','Parlour POS'),('allow_negative_stock','0')");
}];
