<?php

declare(strict_types=1);

return ['up' => static function (\PDO $pdo): void {
    $queries = [
        "CREATE TABLE expense_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "CREATE TABLE purchases (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_number VARCHAR(40) NOT NULL UNIQUE, supplier_id BIGINT UNSIGNED NOT NULL, supplier_invoice_no VARCHAR(100) NULL, purchase_date DATE NOT NULL, subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, tax_total DECIMAL(12,2) NOT NULL DEFAULT 0, grand_total DECIMAL(12,2) NOT NULL DEFAULT 0, payment_status ENUM('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid', created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(supplier_id,supplier_invoice_no), FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE purchase_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(12,3) NOT NULL, unit_price DECIMAL(12,2) NOT NULL, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0, line_total DECIMAL(12,2) NOT NULL, FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB",
        "CREATE TABLE commissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_item_id BIGINT UNSIGNED NOT NULL UNIQUE, staff_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NOT NULL, commission_type ENUM('percentage','fixed') NOT NULL, commission_rate DECIMAL(12,2) NOT NULL, commission_amount DECIMAL(12,2) NOT NULL, status ENUM('unpaid','paid') NOT NULL DEFAULT 'unpaid', paid_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_item_id) REFERENCES invoice_items(id), FOREIGN KEY(staff_id) REFERENCES staff(id), FOREIGN KEY(invoice_id) REFERENCES invoices(id)) ENGINE=InnoDB",
        "CREATE TABLE refunds (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, refund_number VARCHAR(40) NOT NULL UNIQUE, invoice_id BIGINT UNSIGNED NOT NULL, refund_method_id BIGINT UNSIGNED NULL, amount DECIMAL(12,2) NOT NULL, reason VARCHAR(255) NOT NULL, status ENUM('completed','void') NOT NULL DEFAULT 'completed', created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_id) REFERENCES invoices(id), FOREIGN KEY(refund_method_id) REFERENCES payment_methods(id), FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB",
        "CREATE TABLE refund_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, refund_id BIGINT UNSIGNED NOT NULL, invoice_item_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(12,3) NOT NULL, amount DECIMAL(12,2) NOT NULL, return_to_stock TINYINT(1) NOT NULL DEFAULT 0, FOREIGN KEY(refund_id) REFERENCES refunds(id) ON DELETE CASCADE, FOREIGN KEY(invoice_item_id) REFERENCES invoice_items(id)) ENGINE=InnoDB",
        "CREATE TABLE discounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, code VARCHAR(40) NULL UNIQUE, discount_type ENUM('percentage','fixed') NOT NULL, discount_value DECIMAL(12,2) NOT NULL, starts_on DATE NULL, ends_on DATE NULL, minimum_bill DECIMAL(12,2) NOT NULL DEFAULT 0, maximum_discount DECIMAL(12,2) NULL, usage_limit INT UNSIGNED NULL, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB",
        "ALTER TABLE customers ADD COLUMN dob DATE NULL, ADD COLUMN address TEXT NULL",
        "ALTER TABLE services ADD COLUMN description TEXT NULL",
        "ALTER TABLE products ADD COLUMN barcode VARCHAR(100) NULL UNIQUE, ADD COLUMN brand VARCHAR(100) NULL",
        "ALTER TABLE expenses ADD COLUMN category_id BIGINT UNSIGNED NULL, ADD COLUMN payment_method_id BIGINT UNSIGNED NULL, ADD COLUMN reference_no VARCHAR(100) NULL, ADD COLUMN attachment_path VARCHAR(255) NULL, ADD CONSTRAINT fk_expense_category FOREIGN KEY(category_id) REFERENCES expense_categories(id) ON DELETE SET NULL, ADD CONSTRAINT fk_expense_payment_method FOREIGN KEY(payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL",
    ];
    foreach ($queries as $query) { $pdo->exec($query); }
    $pdo->exec("INSERT INTO expense_categories (name) VALUES ('Rent'),('Utilities'),('Salary'),('Maintenance'),('Marketing'),('Cleaning'),('Miscellaneous')");
}];
